name:                twitc-hs
version:             0.1.0.0
github:              "callummance/twitc-hs"
license:             BSD3
author:              "Callum"
maintainer:          "callummance@gmail.comj"
copyright:           "2019 Callum"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/twitc-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- servant
- servant-server
- servant-client

library:
  source-dirs: src

executables:
  twitc-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitc-hs

tests:
  twitc-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitc-hs
